### ISSUE TITLE
[BUG] Manufacturer and Model values are flipped

### ISSUE THREAD

**Issue by ian-young** [ms1450/CommandConnectorCompatibilityCalculator#18]
**Describe the bug**
The model is listed under the manufacturer column and vice versa.

**To Reproduce**

Run the script against [customer_sheet_1.csv](https://github.com/ms1450/CommandConnectorCompatibilityCalculator/blob/main/Camera%20Compatibility%20Sheets/customer_sheet_1.csv)

**Expected behavior**
Manufacturer appears under the appropriate column. Currently Axis is appearing as a Model and not a Manufacturer.

**Screenshots**

![Screenshot 2024-08-28 at 1 01 27 PM](https://github.com/user-attachments/assets/096fc586-976c-4e21-bdd7-7cf00f797c6a)

**Comment by ms1450** [comment]
Should be fixed with the latest commit!
