### ISSUE TITLE
[FR] GUI

### ISSUE THREAD

**Issue by ian-young** [ms1450/CommandConnectorCompatibilityCalculator#23]
# GUI

## What's included
- [x] Compatibility list is printed clearly and with the same or improved formatting
- [x] Command connector recommendation is shown
   - [x] Excess channels are visible
- [x] Modern feeling UI with appropriate padding
- [x] Dynamic resizing with the appropriate scroll bars
- [x] Drag and drop functionality
   - [x] File name is visible
- [x] Easy navigation (toolbar menu vs buttons)
   - [x] Restructure so calculations are ran only once and passed through tabulation on button press
- [x] Scalable
- [x] Add how much retention is required to dynamically set the variable
   - [x] Warning is present if they attempt to go above 90 or below 30 days.

**Comment by ian-young** [comment]
Commit 54fde436ecb49a7ad717e72ee78e08498fcb96ca adds the `Spinbox` to dynamically set retention. Its bounds are set to `30` and `90` which relate to what the Command Connector can do. A pop up may be appropriate if the user goes in and sets a value that violates these bounds.

> [!NOTE]
> Text needs to be added to indicate to the user that the `Spinbox` is for setting the retention in days.

> [!IMPORTANT]
>It is also important that the user understands that retention needs to be an `int` value since they cannot set `30.5` days worth of retention for example

**Comment by ms1450** [comment]
Added Command Connectors, limitation to the retention period (users can only select 30, 60 or 90 days). Also cleaned up UI.
